<?php
echo $this->headTitle('ZF2 '. $this->translate('Sticky Notes'))->setSeparator(' - ')->setAutoEscape(false)  // change Skeleton Application to Sticky Notes ?>

// and change line 32

<a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Sticky Notes') // change Skeleton Application to Sticky Notes ?>
</a>
<?php
headLink(array('rel' => 'shortcut icon', 'type' =>
'image/vnd.microsoft.icon', 'href' => $this->basePath() .
'/images/favicon.ico')) ->prependStylesheet($this->basePath() .
'/css/StickyNotes.css') // add this line
->prependStylesheet($this->basePath() .
'/css/bootstrap-responsive.min.css')
->prependStylesheet($this->basePath() . '/css/style.css')
->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
